apiVersion: v1
kind: Service
metadata:
  name: beginner-html-site-service
spec:
  type: NodePort
  selector:
    app: beginner-html-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
